@Restaurants.API_HostAddress = https://localhost:7123
@token = CfDJ8ECy0YONWbVMiS2uquf0HFyGn0WdjenWQ7UBXhBwyDPdaryYH42HDomRyC1k7TqUdOVBCfN4T2MHqkBQt2qH8EoRcoOIyooXT7RM8_Ywd0_hKelRb7MzjMfmr1_YxUW839wI9JeEcTItpU6qMfFjafab0aLK2gXYsEX6IVqTVJoyLIMv9ClJWpkqthHCWhdBd828pLp1YAbf-vaen5JCwg8fjzm217GlJ5Zt-T8bRHVBFyeoirPAVB5Slc8INFT7ILN-4N7rigsd3k-rFGKm8RcE_P-hMIpxmkutxbzmcFQGb5vzdtwPbzeOoff0Jc3aHqJt0I-vRuCU_d51eN4eHF0awCNH7qjBs7OudmYflw7L6DyBwunPcj0Ivab15v9sErtfs0W_k5wYA8irqbzVns8BbZ-lp7OCHKlm9dyU-_pUPwf3xeR4DHzMtUV1w6zAgoXsXOo8z2b7AyHBO0Za0yvt0eN6u2LnpxZUfFiOlZMIeruQ6nV9Mu2t6CGRdlN9BuKEOtUVE3PGlJS0GuPrjQ_vpW9G8JDyrnt8OJvQHc3vZ-us8TNKkJC1p-gyu3Kbv5S3vpMM89jOiy47jS0Idx9nOe-W4BilfojBvTiU5o-33UVvZhUjYSebvQkk3Gpc0LzuoyX2yKxz2GFjCorT131iKNof6g7HhmFeQa13ohyvMJJD0StMyeoWqOZVuaNDiFZtsjfL7d83YFljsrIE2Jnqv-Bdfex4SaICOoTPEdkc93_D4FtWXwadzK0rDP1c2C5qrsxIxgKxuqn69Lrag8M_7Bsn-aOP-r8Iros_dnTH



###
GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=&pageNumber=1&pageSize=10&sortBy=Name
Authorization: Bearer {{token}}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes/
Authorization: Bearer {{token}}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes/8

###
POST {{Restaurants.API_HostAddress}}/api/restaurants/
Content-type: application/json; charset=utf-8
Accept: application/json
Authorization: Bearer {{token}}
{
 "Name": "owner2 restaurants-2 added ",
 "Category": "Australian",
 "Description": "owner2 restaurant-2 tasty",
 "ContactEmail": "test9@email.com",
 "City" : "Gandhinagar"
}

###
POST {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes
Content-type: application/json; charset=utf-8
Accept: application/json
{
    "Name" : "Samosa special",
    "Description" : " Paneer made samosa spicy",
    "Price" : 45.25,
    "KiloCalories" : 22
}


###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/16
Authorization: Bearer {{token}}
###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6/dishes/



###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/16
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "Name": "Updated mild namkeen",
    "Description": "Extra sweet poha tasty",
    "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
    "email": "owner2@test.com",
    "password": "P@ssword1!"
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
    "email": "owner2@test.com",
    "password": "P@ssword1!"
}

###
PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "Nationality": "German",
    "DateOfBirth": "1998-03-12"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}

###
